NullaGroupHome/Areas/Product/Controllers/BetterHUDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NullaGroupHome.Areas.Product.Controllers
{
    public partial class BetterHUDController : Controller
    {
        // GET: Product/BetterHUD
        public ActionResult Index()
        {
            return View();
        }
    }
}

NullaGroupHome/Areas/Product/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;
using NullaGroupHome.Areas.Product.ViewModel;
using NullaGroupHome.Models;

namespace NullaGroupHome.Areas.Product.Controllers
{
    public class HomeController : Controller
    {
        private readonly ModInfoEntities _modInfoDb = new ModInfoEntities();
        protected override void OnException(ExceptionContext filterContext)
        {
            filterContext.Result = View("ExceptionPage", new ProductExceptionInfo(filterContext.Exception));
            filterContext.ExceptionHandled = true;
            base.OnException(filterContext);
        }

        // GET: Product/Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Download(string modname)
        {
            if (string.IsNullOrEmpty(modname) || !Directory.Exists(Server.MapPath("~/Areas/Product/Files") + $"\\{modname}"))
            {
                throw new ModInexistenceException(modname);
            }
            var model =
                Directory.GetDirectories(Server.MapPath($"/Areas/Product/Files/{modname}"))
                    .Select(dire => new DownloadGameVersion(Server, _modInfoDb, modname, Path.GetFileName(dire)));
            return View(model);
        }

        public ActionResult Image(string modname)
        {
            if (string.IsNullOrEmpty(modname) || _modInfoDb.ModNames.All(mn => mn.Name != modname))
            {
                throw new ModInexistenceException(modname);
            }
            IEnumerable<ModImage> model = _modInfoDb.ModImages.Where(mi => mi.ModName.Name == modname).ToList();
            model = model.Skip(1);
            return View(model);
        }

        public ActionResult GetImage(int id)
        {
            return new FileContentResult(_modInfoDb.ModImages.SingleOrDefault(mi => mi.Id == id).Image, "image/jpeg");
        }

        public ActionResult ExceptionPage()
        {
            return View();
        }

        public ActionResult UploadModImage()
        {
            return View(_modInfoDb.ModImages.Select(mi => mi.ModName.Name).Distinct());
        }

        [HttpPost]
        public ActionResult ModImageUploader(FormCollection form)
        {
            var modname = form["modname"];
            var mi = new ModImage
            {
                ModId = _modInfoDb.ModNames.SingleOrDefault(mn => mn.Name == modname).Id,
                Uploader = form["uploader"],
                UploadDate = DateTime.Now,
                Information = form["information"],
                Image = Request.Files["image"].InputStream.GetBytes()
            };
            _modInfoDb.ModImages.Add(mi);
            _modInfoDb.SaveChanges();
            return UploadSuccess(modname);
        }

        public ActionResult UploadSuccess(string modname)
        {
            return View();
        }
    }
}

NullaGroupHome/Areas/Product/Controllers/KeyCraftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NullaGroupHome.Areas.Product.Controllers
{
    public partial class KeyCraftController : Controller
    {
        // GET: Product/KeyCraft
        public ActionResult Index()
        {
            return View();
        }
    }
}

NullaGroupHome/Areas/Product/Controllers/KotoriTechController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NullaGroupHome.Areas.Product.Controllers
{
    public partial class KotoriTechController : Controller
    {
        // GET: Product/KotoriTech
        public ActionResult Index()
        {
            return View();
        }
    }
}

NullaGroupHome/Areas/Product/Controllers/NullaCoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NullaGroupHome.Areas.Product.Controllers
{
    public partial class NullaCoreController : Controller
    {
        // GET: Product/NullaCore
        public ActionResult Index()
        {
            return View();
        }
    }
}

NullaGroupHome/Areas/Product/Controllers/RailGunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NullaGroupHome.Areas.Product.Controllers
{
    public partial class RailGunController : Controller
    {
        // GET: Product/RainGun
        public ActionResult Index()
        {
            return View();
        }
    }
}

NullaGroupHome/Areas/Product/Views/Shared/Product/_LayoutBetterHUD.cshtml
@{
    Layout = "~/Areas/Product/Views/Shared/_LayoutProduct.cshtml";

}

<script>
    setBetterHUDTitle("@ViewBag.Title");
</script>
<div>
    @RenderBody()
</div>

@section Navbar
{
    <li>
        <a href="/Product/BetterHUD" target="_blank">
            <img src="/Areas/Product/Content/Image/Icon/BetterHUD.jpg" height="80px" width="120px" />
        </a>
    </li>
<li id="MenuHome">@Html.ActionLink("简 介", "Index", "BetterHUD", new { area = "Product" }, null)</li>
<li id="MenuDownload">@Html.ActionLink("下 载", "Download", "Home", new { area = "Product", modname = "BetterHUD" }, null)</li>
<li id="MenuImage">@Html.ActionLink("图 片", "Image", "Home", new { area = "Product", modname = "BetterHUD" }, null)</li>
}

NullaGroupHome/Areas/Product/Views/Shared/Product/_LayoutKeyCraft.cshtml
@{
    Layout = "~/Areas/Product/Views/Shared/_LayoutProduct.cshtml";

}

<script>
    setKeyCraftTitle("@ViewBag.Title");
</script>
<div>
    @RenderBody()
</div>

@section Navbar
{
    <li>
        <a href="/Product/KeyCraft" target="_blank">
            <img src="/Areas/Product/Content/Image/Icon/KeyCraft.jpg" height="80px" width="120px" />
        </a>
    </li>
    <li id="MenuHome">@Html.ActionLink("简 介", "Index", "KeyCraft", new { area = "Product" }, null)</li>
    <li id="MenuDownload">@Html.ActionLink("下 载", "Download", "Home", new { area = "Product", modname = "KeyCraft" }, null)</li>
    <li id="MenuImage">@Html.ActionLink("图 片", "Image", "Home", new { area = "Product", modname = "KeyCraft" }, null)</li>
    <li id="MenuWiki"><a>Wiki</a></li>
}

NullaGroupHome/Areas/Product/Views/Shared/Product/_LayoutKotoriTech.cshtml
@{
    Layout = "~/Areas/Product/Views/Shared/_LayoutProduct.cshtml";

}

<script>
    setBetterHUDTitle("@ViewBag.Title");
</script>
<div>
    @RenderBody()
</div>

@section Navbar
{
    <li>
        <a href="/Product/KotoriTech" target="_blank">
            <img src="/Areas/Product/Content/Image/Icon/KotoriTech.jpg" height="80px" width="120px" />
        </a>
    </li>
<li id="MenuHome">@Html.ActionLink("简 介", "Index", "KotoriTech", new { area = "Product" }, null)</li>
<li id="MenuDownload">@Html.ActionLink("下 载", "Download", "Home", new { area = "Product", modname = "KotoriTech" }, null)</li>
<li id="MenuImage">@Html.ActionLink("图 片", "Image", "Home", new { area = "Product", modname = "KotoriTech" }, null)</li>
}

NullaGroupHome/Areas/Product/Views/Shared/Product/_LayoutNullaCore.cshtml
@{
    Layout = "~/Areas/Product/Views/Shared/_LayoutProduct.cshtml";

}

<script>
    setNullaCoreTitle("@ViewBag.Title");
</script>
<div>
    @RenderBody()
</div>

@section Navbar
{
    <li>
        <a href="/Product/NullaCore" target="_blank">
            <img src="/Areas/Product/Content/Image/Icon/NullaCore.jpg" height="80px" width="120px" />
        </a>
    </li>
    <li id="MenuHome">@Html.ActionLink("简 介", "Index", "NullaCore", new { area = "Product" }, null)</li>
    <li id="MenuDownload">@Html.ActionLink("下 载", "Download", "Home", new { area = "Product", modname = "NullaCore" }, null)</li>
}

NullaGroupHome/Areas/Product/Views/Shared/Product/_LayoutRailGun.cshtml
@{
    Layout = "~/Areas/Product/Views/Shared/_LayoutProduct.cshtml";

}

<script>
    setRailGunTitle("@ViewBag.Title");
</script>
<div>
    @RenderBody()
</div>

@section Navbar
{
    <li>
        <a href="/Product/RailGun" target="_blank">
            <img src="/Areas/Product/Content/Image/Icon/RailGun.jpg" height="80px" width="120px" />
        </a>
    </li>
<li id="MenuHome">@Html.ActionLink("简 介", "Index", "RailGun", new { area = "Product" }, null)</li>
<li id="MenuDownload">@Html.ActionLink("下 载", "Download", "Home", new { area = "Product", modname = "RailGun" }, null)</li>
<li id="MenuImage">@Html.ActionLink("图 片", "Image", "Home", new { area = "Product", modname = "RailGun" }, null)</li>
}